### ISSUE TITLE
UTF8 (by Anton Ivanov)

### ISSUE THREAD

**Issue by glejeune** [glejeune/Ruby-Graphviz#12]
I seem to have a problem with utf-8 labels.  The following renders fine:   a [label="ε"]; however when I pass  {:label=>'ε'} to add_node, the output has 
[label="\316\265"] which renders as a decimal value.

**Comment by vanboom** [comment]
See my issue #115 and PR #151.  Encoding issues occur when labels include UTF8 text and Graphviz is producing a text file (SVG).  Open3.capture3 when run in binmode=true returns ASCII-8BIT result.  Binmode needs to be disabled when requesting a text based output format.
