### ISSUE TITLE
Any way to set edge direction?

### ISSUE THREAD

**Issue by nathanl** [glejeune/Ruby-Graphviz#120]
When running the `digraph` example in the README, I don't see any way to set the edge direction.

The direction is the same regardless of the order of these two node arguments.

``` ruby
g.add_edges( hello, world )
# vs
g.add_edges( world, hello )
```

In contrast, if I use `dot` directly, these two things produce different outputs:

``` dot
digraph graphname{
  a -> b;
}

// vs

digraph graphname{
  b -> a;
}
```

``` bash
dot mygraphdata.dot -T svg -o some.svg
```

I tried reading the code to find a way to set edge direction, but didn't see a way.

**Comment by 6kamhh** [comment]
Do you mean something like this?
`g.add_edges( hello, world, dir: "forward")`

Options include forward, back, both, none

**Comment by nathanl** [comment]
Thanks!
