### ISSUE TITLE
Error building ruby-graphviz

### ISSUE THREAD

**Issue by caolandix** [glejeune/Ruby-Graphviz#141]
When i execute gem install ruby-graphviz I get the following error:

WARNING:  See http://guides.rubygems.org/specification-reference/ for help
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    ["AUTHORS.rdoc", "CHANGELOG.rdoc", "COPYING.rdoc", "README.rdoc"] are not files

Ruby Version: ruby 2.3.7p456 (2018-03-28 revision 63024) [x86_64-linux]

**Comment by glejeune** [comment]
Hello @caolandix could you give me more info about your environment ? I can't reproduce the problem on my Ubuntu 18.04 with rbenv and ruby 2.3.7.

**Comment by deivid-rodriguez** [comment]
This will be fixed by #146.
