### ISSUE TITLE
How to unflatten the graph?

### ISSUE THREAD

**Issue by simonszu** [glejeune/Ruby-Graphviz#67]
I have a graph with one central element and different surrounding elements, all linked to the center element. 
My output file is a 10k pixel wide image with two rows. One with the center element, and one with all the surrounding elements. 

I can't find any documentation how to change the layout so that the center element is indeed in the center of a circle, built with the surrounding elements.

There is an unflatten preprocessor in the graphviz package, maybe this is the solution, but i can't figure it out how to use it inside my script...

Or is there anything else i do not see?

**Comment by rnovak1988** [comment]
Have you tried using the neato layout engine?

```ruby
GraphViz::options( :use => 'neato' )
graph = GraphViz.new(:graph)
...
```
