### ISSUE TITLE
Relicense under the MIT license.

### ISSUE THREAD

**Issue by ioquatix** [glejeune/Ruby-Graphviz#81]
This is more of a suggestion than a bug. Have you considered relicensing the project under the MIT license? I like to release my software under the MIT license but to combine with graphviz library causes my code to need to be released under GPL too. I prefer people to have access to my code under a less restrictive license, e.g. MIT, BSD, etc.

Thanks, Samuel.

**Comment by ipitythefoo** [comment]
@ioquatix Thank you so much for doing this.  We had to switch away from ruby-graphviz because of the GPL license and it was great that you did the work to release an equivalent MIT-licensed gem.

**Comment by ioquatix** [comment]
@ipitythefoo no problem, please feel free to improve graphviz gem it's pretty minimal.

**Comment by thbar** [comment]
@glejeune any chance you could still consider relicensing to MIT, or maybe a multiple license (MIT/GPL) like I think Prawn did? I do realize that it could require to contact all authors, but it would make the use of Ruby-Graphviz in contexts where GPL is not possible. Thanks!
